vich_uploader:
    db_driver: orm
    mappings:
        postuler_resume:
            uri_prefix: /resumes
            upload_destination: '%kernel.project_dir%/public/resumes'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        talent_image:
            uri_prefix: /image
            upload_destination: '%kernel.project_dir%/public/image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
